Insert into house(housePass, Latitude, Longitude, QR) values ('House123', 53.4757667, -2.2441503, 'House123');
Insert into house(housePass, Latitude, Longitude, QR) values ('House123', 53.4630589, -2.2935288, 'House234');
Insert into house(housePass, Latitude, Longitude, QR) values (AES_ENCRYPT('House123', 53.46305546, -2.2935289098, 'House345'));
Insert into users(UserPassword, Lastname, Firstname, Priority, Email, HouseId) values ('User123', 'Roberts','Nicholas', 1, 'nick12345@hotmail.co.uk', 1);
Insert into users(UserPassword, Lastname, Firstname, Priority, Email, HouseId) v alues ('User123', 'Green','Karl', 2, 'Karl12345@hotmail.co.uk', 2);
Insert into nest(Temperature, automaticStatus, HouseId) values (30, true, 1);
Insert into nest(Temperature, automaticStatus, HouseId) values (32, true, 2);
Insert into sensors(SensorID,SensorName, SensorMethod, Portnumber, SensorPriority, HouseID) values (1,'motionSensor', 'onChanged', 1, 1, 1);
Insert into sensors(SensorID,SensorName, SensorMethod, Portnumber, SensorPriority, HouseID) values (2,'touchSensor', 'average', 2, 2, 1);
Insert into sensors(SensorID,SensorName, SensorMethod, Portnumber, SensorPriority, HouseID) values (3,'lightSensor', 'onChanged', 3, 3, 1);
Insert into sensors(SensorID,SensorName, SensorMethod, Portnumber, SensorPriority, HouseID) values (4,'lightSensor', 'average', 2, 1, 2);
Insert into sensorValues(SensorValue, SensorID) values (451, 1);
Insert into sensorValues(SensorValue, SensorID) values (534, 2);
Insert into PhilipsHue(Lightname, Brightness, Saturation, Red, Blue, Green, Power, AutomaticStatus, HouseId) values ('Bulb1', 234, 186, 186, 192, 157, True, True, 1);
Insert into PhilipsHue(Lightname, Brightness, Saturation, Red, Blue, Green, Power, AutomaticStatus, HouseId) values ('Bulb1', 245, 192, 224, 245, 236, True, false, 2);
Insert into PrefLighting(Brightness, Saturation, Red, Blue, Green, actionMethod, actionPriority, UserID) Values (10, 15, 201, 205, 234, 'lighting', 2, 1);
Insert into PrefLighting(Brightness, Saturation, Red, Blue, Green, actionMethod, actionPriority, UserID) Values (20, 10, 225, 223, 240, 'motion', 1, 2);
Insert into PrefTemp(TargetTemp, actionMethod, actionPriority, UserID) Values (30, 'location', 1, 1);
Insert into PrefTemp(TargetTemp, actionMethod, actionPriority, UserID) Values (20, 'motion', 2, 2);
